//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Languages.Database {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminBreadcrumbs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminBreadcrumbs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Languages.Database.AdminBreadcrumbs", typeof(AdminBreadcrumbs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AccountsEditAction {
            get {
                return ResourceManager.GetString("AccountsEditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsEditController {
            get {
                return ResourceManager.GetString("AccountsEditController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify account.
        /// </summary>
        public static string AccountsEditDescription {
            get {
                return ResourceManager.GetString("AccountsEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        public static string AccountsEditTitle {
            get {
                return ResourceManager.GetString("AccountsEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string AccountsHomeAction {
            get {
                return ResourceManager.GetString("AccountsHomeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsHomeController {
            get {
                return ResourceManager.GetString("AccountsHomeController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsHomeTitle {
            get {
                return ResourceManager.GetString("AccountsHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string AccountsIndexDescription {
            get {
                return ResourceManager.GetString("AccountsIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string AccountsViewAction {
            get {
                return ResourceManager.GetString("AccountsViewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsViewController {
            get {
                return ResourceManager.GetString("AccountsViewController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information.
        /// </summary>
        public static string AccountsViewDescription {
            get {
                return ResourceManager.GetString("AccountsViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View account.
        /// </summary>
        public static string AccountsViewTitle {
            get {
                return ResourceManager.GetString("AccountsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BlacklistAddAction {
            get {
                return ResourceManager.GetString("BlacklistAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string BlacklistAddController {
            get {
                return ResourceManager.GetString("BlacklistAddController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add domain.
        /// </summary>
        public static string BlacklistAddDescription {
            get {
                return ResourceManager.GetString("BlacklistAddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add blacklist domain.
        /// </summary>
        public static string BlacklistAddTitle {
            get {
                return ResourceManager.GetString("BlacklistAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string BlacklistEditAction {
            get {
                return ResourceManager.GetString("BlacklistEditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string BlacklistEditController {
            get {
                return ResourceManager.GetString("BlacklistEditController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit domain.
        /// </summary>
        public static string BlacklistEditDescription {
            get {
                return ResourceManager.GetString("BlacklistEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit blacklist domain.
        /// </summary>
        public static string BlacklistEditTitle {
            get {
                return ResourceManager.GetString("BlacklistEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BlacklistIndexAction {
            get {
                return ResourceManager.GetString("BlacklistIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string BlacklistIndexController {
            get {
                return ResourceManager.GetString("BlacklistIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklisted domains.
        /// </summary>
        public static string BlacklistIndexDescription {
            get {
                return ResourceManager.GetString("BlacklistIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string BlacklistIndexTitle {
            get {
                return ResourceManager.GetString("BlacklistIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CategoriesAddAction {
            get {
                return ResourceManager.GetString("CategoriesAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesAddController {
            get {
                return ResourceManager.GetString("CategoriesAddController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        public static string CategoriesAddDescription {
            get {
                return ResourceManager.GetString("CategoriesAddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        public static string CategoriesAddTitle {
            get {
                return ResourceManager.GetString("CategoriesAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string CategoriesEditAction {
            get {
                return ResourceManager.GetString("CategoriesEditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesEditController {
            get {
                return ResourceManager.GetString("CategoriesEditController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string CategoriesEditDescription {
            get {
                return ResourceManager.GetString("CategoriesEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string CategoriesEditTitle {
            get {
                return ResourceManager.GetString("CategoriesEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesIndexAction {
            get {
                return ResourceManager.GetString("CategoriesIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesIndexController {
            get {
                return ResourceManager.GetString("CategoriesIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string CategoriesIndexDescription {
            get {
                return ResourceManager.GetString("CategoriesIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesIndexTitle {
            get {
                return ResourceManager.GetString("CategoriesIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        public static string DashBoardIndexDescription {
            get {
                return ResourceManager.GetString("DashBoardIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string ElmahIndexAction {
            get {
                return ResourceManager.GetString("ElmahIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah.
        /// </summary>
        public static string ElmahIndexController {
            get {
                return ResourceManager.GetString("ElmahIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged errors.
        /// </summary>
        public static string ElmahIndexDescription {
            get {
                return ResourceManager.GetString("ElmahIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah.
        /// </summary>
        public static string ElmahIndexTitle {
            get {
                return ResourceManager.GetString("ElmahIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filemanager.
        /// </summary>
        public static string FileManagerDescription {
            get {
                return ResourceManager.GetString("FileManagerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string FileManagerIndexAction {
            get {
                return ResourceManager.GetString("FileManagerIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File manager.
        /// </summary>
        public static string FilemanagerIndexController {
            get {
                return ResourceManager.GetString("FilemanagerIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File manager.
        /// </summary>
        public static string FileManagerIndexTitle {
            get {
                return ResourceManager.GetString("FileManagerIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string HomeDashboardAction {
            get {
                return ResourceManager.GetString("HomeDashboardAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string HomeDashboardController {
            get {
                return ResourceManager.GetString("HomeDashboardController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string HomeDashboardTitle {
            get {
                return ResourceManager.GetString("HomeDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string LinksAddAction {
            get {
                return ResourceManager.GetString("LinksAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string LinksAddController {
            get {
                return ResourceManager.GetString("LinksAddController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add partner.
        /// </summary>
        public static string LinksAddDescription {
            get {
                return ResourceManager.GetString("LinksAddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link.
        /// </summary>
        public static string LinksAddtitle {
            get {
                return ResourceManager.GetString("LinksAddtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string LinksEditAction {
            get {
                return ResourceManager.GetString("LinksEditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string LinksEditController {
            get {
                return ResourceManager.GetString("LinksEditController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit partner.
        /// </summary>
        public static string LinksEditDescription {
            get {
                return ResourceManager.GetString("LinksEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit link.
        /// </summary>
        public static string LinksEditTitle {
            get {
                return ResourceManager.GetString("LinksEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string LinksIndexAction {
            get {
                return ResourceManager.GetString("LinksIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string LinksIndexController {
            get {
                return ResourceManager.GetString("LinksIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string LinksIndexDescription {
            get {
                return ResourceManager.GetString("LinksIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string LinksIndexTitle {
            get {
                return ResourceManager.GetString("LinksIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string NewsAddAction {
            get {
                return ResourceManager.GetString("NewsAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsAddController {
            get {
                return ResourceManager.GetString("NewsAddController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add newsarticle.
        /// </summary>
        public static string NewsAddDescription {
            get {
                return ResourceManager.GetString("NewsAddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add article.
        /// </summary>
        public static string NewsAddTitle {
            get {
                return ResourceManager.GetString("NewsAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string NewsEditAction {
            get {
                return ResourceManager.GetString("NewsEditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsEditController {
            get {
                return ResourceManager.GetString("NewsEditController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit newsarticle.
        /// </summary>
        public static string NewsEditDescription {
            get {
                return ResourceManager.GetString("NewsEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article.
        /// </summary>
        public static string NewsEditTitle {
            get {
                return ResourceManager.GetString("NewsEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NewsIndexAction {
            get {
                return ResourceManager.GetString("NewsIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsIndexController {
            get {
                return ResourceManager.GetString("NewsIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NewsIndexDescription {
            get {
                return ResourceManager.GetString("NewsIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsIndexTitle {
            get {
                return ResourceManager.GetString("NewsIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PagesAddAction {
            get {
                return ResourceManager.GetString("PagesAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string PagesAddController {
            get {
                return ResourceManager.GetString("PagesAddController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add page.
        /// </summary>
        public static string PagesAddDescription {
            get {
                return ResourceManager.GetString("PagesAddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add page.
        /// </summary>
        public static string PagesAddTitle {
            get {
                return ResourceManager.GetString("PagesAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PagesEditAction {
            get {
                return ResourceManager.GetString("PagesEditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string PagesEditController {
            get {
                return ResourceManager.GetString("PagesEditController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit page.
        /// </summary>
        public static string PagesEditDescription {
            get {
                return ResourceManager.GetString("PagesEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit page.
        /// </summary>
        public static string PagesEditTitle {
            get {
                return ResourceManager.GetString("PagesEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PagesIndexAction {
            get {
                return ResourceManager.GetString("PagesIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string PagesIndexController {
            get {
                return ResourceManager.GetString("PagesIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PagesIndexDescription {
            get {
                return ResourceManager.GetString("PagesIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string PagesIndexTitle {
            get {
                return ResourceManager.GetString("PagesIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string PluginIndexAction {
            get {
                return ResourceManager.GetString("PluginIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginIndexController {
            get {
                return ResourceManager.GetString("PluginIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage plugins.
        /// </summary>
        public static string PluginIndexDescription {
            get {
                return ResourceManager.GetString("PluginIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginIndexTitle {
            get {
                return ResourceManager.GetString("PluginIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string PluginsActiveAction {
            get {
                return ResourceManager.GetString("PluginsActiveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginsActiveController {
            get {
                return ResourceManager.GetString("PluginsActiveController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active plugins.
        /// </summary>
        public static string PluginsActiveDescription {
            get {
                return ResourceManager.GetString("PluginsActiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginsActiveTitle {
            get {
                return ResourceManager.GetString("PluginsActiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string PluginsInActiveAction {
            get {
                return ResourceManager.GetString("PluginsInActiveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginsInActiveController {
            get {
                return ResourceManager.GetString("PluginsInActiveController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive plugins.
        /// </summary>
        public static string PluginsInActiveDescription {
            get {
                return ResourceManager.GetString("PluginsInActiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginsInActiveTitle {
            get {
                return ResourceManager.GetString("PluginsInActiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string PluginsIndexAction {
            get {
                return ResourceManager.GetString("PluginsIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginsIndexController {
            get {
                return ResourceManager.GetString("PluginsIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed plugins.
        /// </summary>
        public static string PluginsIndexDescription {
            get {
                return ResourceManager.GetString("PluginsIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginsIndexTitle {
            get {
                return ResourceManager.GetString("PluginsIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string PluginsUpdatesDescription {
            get {
                return ResourceManager.GetString("PluginsUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string PluginUpdatesAction {
            get {
                return ResourceManager.GetString("PluginUpdatesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginUpdatesController {
            get {
                return ResourceManager.GetString("PluginUpdatesController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin updates.
        /// </summary>
        public static string PluginUpdatesTitle {
            get {
                return ResourceManager.GetString("PluginUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PollAddAction {
            get {
                return ResourceManager.GetString("PollAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string PollAddController {
            get {
                return ResourceManager.GetString("PollAddController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PollAddDescription {
            get {
                return ResourceManager.GetString("PollAddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string PollAddTitle {
            get {
                return ResourceManager.GetString("PollAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PollEditAction {
            get {
                return ResourceManager.GetString("PollEditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string PollEditController {
            get {
                return ResourceManager.GetString("PollEditController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PollEditDescription {
            get {
                return ResourceManager.GetString("PollEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string PollEditTitle {
            get {
                return ResourceManager.GetString("PollEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string PollIndexAction {
            get {
                return ResourceManager.GetString("PollIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string PollIndexController {
            get {
                return ResourceManager.GetString("PollIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string PollIndexDescription {
            get {
                return ResourceManager.GetString("PollIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string PollIndexTitle {
            get {
                return ResourceManager.GetString("PollIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string PollViewAction {
            get {
                return ResourceManager.GetString("PollViewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string PollViewController {
            get {
                return ResourceManager.GetString("PollViewController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string PollViewDescription {
            get {
                return ResourceManager.GetString("PollViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string PollViewTitle {
            get {
                return ResourceManager.GetString("PollViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ReportsIndexAction {
            get {
                return ResourceManager.GetString("ReportsIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsIndexController {
            get {
                return ResourceManager.GetString("ReportsIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ReportsIndexDescription {
            get {
                return ResourceManager.GetString("ReportsIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsIndexTitle {
            get {
                return ResourceManager.GetString("ReportsIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ReportsViewAction {
            get {
                return ResourceManager.GetString("ReportsViewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsViewController {
            get {
                return ResourceManager.GetString("ReportsViewController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report information.
        /// </summary>
        public static string ReportsViewDescription {
            get {
                return ResourceManager.GetString("ReportsViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View report.
        /// </summary>
        public static string ReportsViewTitle {
            get {
                return ResourceManager.GetString("ReportsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify settings.
        /// </summary>
        public static string SettingsEditDescription {
            get {
                return ResourceManager.GetString("SettingsEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string SettingsIndexAction {
            get {
                return ResourceManager.GetString("SettingsIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsIndexController {
            get {
                return ResourceManager.GetString("SettingsIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Settings.
        /// </summary>
        public static string SettingsIndexDescription {
            get {
                return ResourceManager.GetString("SettingsIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsIndexTitle {
            get {
                return ResourceManager.GetString("SettingsIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System updates.
        /// </summary>
        public static string SettingsUpdates {
            get {
                return ResourceManager.GetString("SettingsUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string SettingsUpdatesAction {
            get {
                return ResourceManager.GetString("SettingsUpdatesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsUpdatesController {
            get {
                return ResourceManager.GetString("SettingsUpdatesController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string SettingsUpdatesDescription {
            get {
                return ResourceManager.GetString("SettingsUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System updates.
        /// </summary>
        public static string SettingsUpdatesTitle {
            get {
                return ResourceManager.GetString("SettingsUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string ThemesIndexAction {
            get {
                return ResourceManager.GetString("ThemesIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string ThemesIndexController {
            get {
                return ResourceManager.GetString("ThemesIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed themes.
        /// </summary>
        public static string ThemesIndexDescription {
            get {
                return ResourceManager.GetString("ThemesIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string ThemesIndexTitle {
            get {
                return ResourceManager.GetString("ThemesIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string ThemeUpdatesAction {
            get {
                return ResourceManager.GetString("ThemeUpdatesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string ThemeUpdatesController {
            get {
                return ResourceManager.GetString("ThemeUpdatesController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string ThemeUpdatesDescription {
            get {
                return ResourceManager.GetString("ThemeUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme updates.
        /// </summary>
        public static string ThemeUpdatesTitle {
            get {
                return ResourceManager.GetString("ThemeUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string WebsitesEditAction {
            get {
                return ResourceManager.GetString("WebsitesEditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites.
        /// </summary>
        public static string WebsitesEditController {
            get {
                return ResourceManager.GetString("WebsitesEditController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify website.
        /// </summary>
        public static string WebsitesEditDescription {
            get {
                return ResourceManager.GetString("WebsitesEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify website.
        /// </summary>
        public static string WebsitesEditTitle {
            get {
                return ResourceManager.GetString("WebsitesEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string WebsitesIndexAction {
            get {
                return ResourceManager.GetString("WebsitesIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites.
        /// </summary>
        public static string WebsitesIndexController {
            get {
                return ResourceManager.GetString("WebsitesIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string WebsitesIndexDescription {
            get {
                return ResourceManager.GetString("WebsitesIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites.
        /// </summary>
        public static string WebsitesIndexTitle {
            get {
                return ResourceManager.GetString("WebsitesIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string WebsitesViewAction {
            get {
                return ResourceManager.GetString("WebsitesViewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websites.
        /// </summary>
        public static string WebsitesViewController {
            get {
                return ResourceManager.GetString("WebsitesViewController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website information.
        /// </summary>
        public static string WebsitesViewDescription {
            get {
                return ResourceManager.GetString("WebsitesViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View website.
        /// </summary>
        public static string WebsitesViewTitle {
            get {
                return ResourceManager.GetString("WebsitesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string WidgetsActiveAction {
            get {
                return ResourceManager.GetString("WidgetsActiveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string WidgetsActiveController {
            get {
                return ResourceManager.GetString("WidgetsActiveController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active widgets.
        /// </summary>
        public static string WidgetsActiveDescription {
            get {
                return ResourceManager.GetString("WidgetsActiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string WidgetsActiveTitle {
            get {
                return ResourceManager.GetString("WidgetsActiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string WidgetsIndexAction {
            get {
                return ResourceManager.GetString("WidgetsIndexAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string WidgetsIndexController {
            get {
                return ResourceManager.GetString("WidgetsIndexController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed widgets.
        /// </summary>
        public static string WidgetsIndexDescription {
            get {
                return ResourceManager.GetString("WidgetsIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string WidgetsIndexTitle {
            get {
                return ResourceManager.GetString("WidgetsIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string WidgetsUpdatesAction {
            get {
                return ResourceManager.GetString("WidgetsUpdatesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string WidgetsUpdatesController {
            get {
                return ResourceManager.GetString("WidgetsUpdatesController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string WidgetsUpdatesDescription {
            get {
                return ResourceManager.GetString("WidgetsUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget updates.
        /// </summary>
        public static string WidgetsUpdatesTitle {
            get {
                return ResourceManager.GetString("WidgetsUpdatesTitle", resourceCulture);
            }
        }
    }
}
