using System.Web.Mvc;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topsite.Themes.LightBlue.Helpers
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class _Themes_LightBlue_Helpers_HtmlLoadMoreConfig_cshtml
    {

public static System.Web.WebPages.HelperResult GetLoadMoreHtmlConfig(this System.Web.Mvc.HtmlHelper htmlHelper, int startIndex, int? categoryId = null, string searchText = null)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 4 "..\..\Themes\LightBlue\Helpers\HtmlLoadMoreConfig.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <input type=\"hidden\" id=\"categoryID\" value=\"");



#line 5 "..\..\Themes\LightBlue\Helpers\HtmlLoadMoreConfig.cshtml"
     WebViewPage.WriteTo(@__razor_helper_writer, categoryId);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <input type=\"hidden\" id=\"page\" value=\"1\" />\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <input type=\"hidden\" id=\"searchText\" value=\"");



#line 7 "..\..\Themes\LightBlue\Helpers\HtmlLoadMoreConfig.cshtml"
     WebViewPage.WriteTo(@__razor_helper_writer, searchText);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <input type=\"hidden\" id=\"startIndex\" value=\"");



#line 8 "..\..\Themes\LightBlue\Helpers\HtmlLoadMoreConfig.cshtml"
     WebViewPage.WriteTo(@__razor_helper_writer, startIndex);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "\" />\r\n");



#line 9 "..\..\Themes\LightBlue\Helpers\HtmlLoadMoreConfig.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult DisplayNoResultsFoundAlert(this System.Web.Mvc.HtmlHelper htmlHelper)
{
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 12 "..\..\Themes\LightBlue\Helpers\HtmlLoadMoreConfig.cshtml"
 

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <div class=\'alert alert-info\'>\r\n        <h3>");



#line 14 "..\..\Themes\LightBlue\Helpers\HtmlLoadMoreConfig.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Localization.Languages.Views.Shared.Global.Information);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</h3>\r\n        <p>");



#line 15 "..\..\Themes\LightBlue\Helpers\HtmlLoadMoreConfig.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Localization.Languages.HtmlHelpers.HtmlLoadMoreConfig.NoWebsites);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "</p>\r\n    </div>\r\n");



#line 17 "..\..\Themes\LightBlue\Helpers\HtmlLoadMoreConfig.cshtml"

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
