//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Languages.Views.Website {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GetCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Languages.Views.Website.GetCodes", typeof(GetCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API.
        /// </summary>
        public static string Api {
            get {
                return ResourceManager.GetString("Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have an api to let people automatically vote for you server, only a few steps are necessary to configure it..
        /// </summary>
        public static string ApiDescription {
            get {
                return ResourceManager.GetString("ApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will return a false/true/error..
        /// </summary>
        public static string ApiResponse {
            get {
                return ResourceManager.GetString("ApiResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the code in the textarea into your website and let users click the voting image..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download API.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the file by clicking the download button.
        /// </summary>
        public static string InstructionStep1 {
            get {
                return ResourceManager.GetString("InstructionStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip te package and extract it on your harddisk.
        /// </summary>
        public static string InstructionStep2 {
            get {
                return ResourceManager.GetString("InstructionStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the api.php file with a text editor program.
        /// </summary>
        public static string InstructionStep3 {
            get {
                return ResourceManager.GetString("InstructionStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the values: websiteID, username and redirectUrl to your values.
        /// </summary>
        public static string InstructionStep4 {
            get {
                return ResourceManager.GetString("InstructionStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload the file by a ftp program or something else.
        /// </summary>
        public static string InstructionStep5 {
            get {
                return ResourceManager.GetString("InstructionStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let people redirect to the file.
        /// </summary>
        public static string InstructionStep6 {
            get {
                return ResourceManager.GetString("InstructionStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string InstructionStep7 {
            get {
                return ResourceManager.GetString("InstructionStep7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Code.
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optionalRedirectUrl.
        /// </summary>
        public static string optionalRedirectUrl {
            get {
                return ResourceManager.GetString("optionalRedirectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requiredYourWebsiteId.
        /// </summary>
        public static string requiredWebsiteId {
            get {
                return ResourceManager.GetString("requiredWebsiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get your websiteID navigate to Panel &gt; Websites and use the number after your server title.
        /// </summary>
        public static string Tip1 {
            get {
                return ResourceManager.GetString("Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommend to navigate the user to the api file when he/she wants to register for your server.
        /// </summary>
        public static string Tip2 {
            get {
                return ResourceManager.GetString("Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote for us!.
        /// </summary>
        public static string VoteImageAlt {
            get {
                return ResourceManager.GetString("VoteImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string WebsiteDescription {
            get {
                return ResourceManager.GetString("WebsiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string WebsiteId {
            get {
                return ResourceManager.GetString("WebsiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string WebsiteTitle {
            get {
                return ResourceManager.GetString("WebsiteTitle", resourceCulture);
            }
        }
    }
}
