//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Languages.Admin.Views.Themes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Updates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Updates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Languages.Admin.Views.Themes.Updates", typeof(Updates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Updates.
        /// </summary>
        public static string AvailableUpdates {
            get {
                return ResourceManager.GetString("AvailableUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update(s)....
        /// </summary>
        public static string DownloadingUpdates {
            get {
                return ResourceManager.GetString("DownloadingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing updates....
        /// </summary>
        public static string InstallingUpdatesButton {
            get {
                return ResourceManager.GetString("InstallingUpdatesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install update(s).
        /// </summary>
        public static string InstallUpdates {
            get {
                return ResourceManager.GetString("InstallUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are updates available to install. Please click the button: &apos;Install update(s)&apos; to download and install the available updates..
        /// </summary>
        public static string MultipleNotLatestVersionDescription {
            get {
                return ResourceManager.GetString("MultipleNotLatestVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updates have been succesfully installed..
        /// </summary>
        public static string MultipleUpdateInstalledDescription {
            get {
                return ResourceManager.GetString("MultipleUpdateInstalledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates installed.
        /// </summary>
        public static string MultipleUpdateInstalledTitle {
            get {
                return ResourceManager.GetString("MultipleUpdateInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates available.
        /// </summary>
        public static string MultipleUpdatesAvailableTitle {
            get {
                return ResourceManager.GetString("MultipleUpdatesAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates available chief, you are good to go!.
        /// </summary>
        public static string NoUpdatesAvailableDescription {
            get {
                return ResourceManager.GetString("NoUpdatesAvailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are up to date.
        /// </summary>
        public static string NoUpdatesAvailableTitle {
            get {
                return ResourceManager.GetString("NoUpdatesAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available to install. Please click the button: &apos;Install updates(s)&apos; to download and install the available update..
        /// </summary>
        public static string SingleNotLatestVersionDescription {
            get {
                return ResourceManager.GetString("SingleNotLatestVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string SingleUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("SingleUpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update has been succesfully installed..
        /// </summary>
        public static string SingleUpdateInstalledDescription {
            get {
                return ResourceManager.GetString("SingleUpdateInstalledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update installed.
        /// </summary>
        public static string SingleUpdateInstalledTitle {
            get {
                return ResourceManager.GetString("SingleUpdateInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme updates.
        /// </summary>
        public static string ThemeUpdates {
            get {
                return ResourceManager.GetString("ThemeUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more themes couldn&apos;t be updated, please check the error logs for more information..
        /// </summary>
        public static string UpdatingFailedDescription {
            get {
                return ResourceManager.GetString("UpdatingFailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating failed.
        /// </summary>
        public static string UpdatingFailedTitle {
            get {
                return ResourceManager.GetString("UpdatingFailedTitle", resourceCulture);
            }
        }
    }
}
