//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Languages.Business.Date {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Date {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Date() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Languages.Business.Date.Date", typeof(Date).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0} month ago.
        /// </summary>
        public static string addMonth {
            get {
                return ResourceManager.GetString("addMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0} months ago.
        /// </summary>
        public static string addMonths {
            get {
                return ResourceManager.GetString("addMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        public static string MultipleDays {
            get {
                return ResourceManager.GetString("MultipleDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        public static string MultipleHours {
            get {
                return ResourceManager.GetString("MultipleHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        public static string MultipleMinutes {
            get {
                return ResourceManager.GetString("MultipleMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months ago.
        /// </summary>
        public static string MultipleMonths {
            get {
                return ResourceManager.GetString("MultipleMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks ago.
        /// </summary>
        public static string MultipleWeeks {
            get {
                return ResourceManager.GetString("MultipleWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years ago.
        /// </summary>
        public static string MultipleYears {
            get {
                return ResourceManager.GetString("MultipleYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day ago.
        /// </summary>
        public static string SingleDay {
            get {
                return ResourceManager.GetString("SingleDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour ago.
        /// </summary>
        public static string SingleHour {
            get {
                return ResourceManager.GetString("SingleHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute ago.
        /// </summary>
        public static string SingleMinute {
            get {
                return ResourceManager.GetString("SingleMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month ago.
        /// </summary>
        public static string SingleMonth {
            get {
                return ResourceManager.GetString("SingleMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week ago.
        /// </summary>
        public static string SingleWeek {
            get {
                return ResourceManager.GetString("SingleWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years ago.
        /// </summary>
        public static string SingleYear {
            get {
                return ResourceManager.GetString("SingleYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
