//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Languages.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstallModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Languages.Models.InstallModel", typeof(InstallModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronjob.
        /// </summary>
        public static string Cronjob {
            get {
                return ResourceManager.GetString("Cronjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string DatabaseHost {
            get {
                return ResourceManager.GetString("DatabaseHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DatabasePassword {
            get {
                return ResourceManager.GetString("DatabasePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string DatabaseUsername {
            get {
                return ResourceManager.GetString("DatabaseUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string EmailHost {
            get {
                return ResourceManager.GetString("EmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string EmailPassword {
            get {
                return ResourceManager.GetString("EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string EmailPort {
            get {
                return ResourceManager.GetString("EmailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure.
        /// </summary>
        public static string EmailSecure {
            get {
                return ResourceManager.GetString("EmailSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string EmailUsername {
            get {
                return ResourceManager.GetString("EmailUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin verification.
        /// </summary>
        public static string IsAdminVerificationRequired {
            get {
                return ResourceManager.GetString("IsAdminVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User website thumbnails.
        /// </summary>
        public static string IsCreateUserWebsiteThumbnailsEnabled {
            get {
                return ResourceManager.GetString("IsCreateUserWebsiteThumbnailsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email user statistics.
        /// </summary>
        public static string IsEmailingUserStatisticsEnabled {
            get {
                return ResourceManager.GetString("IsEmailingUserStatisticsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update incorrect version.
        /// </summary>
        public static string IsUpdateWhenIncorrectVersionEnabled {
            get {
                return ResourceManager.GetString("IsUpdateWhenIncorrectVersionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Key.
        /// </summary>
        public static string RecaptchaSecretKey {
            get {
                return ResourceManager.GetString("RecaptchaSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Key.
        /// </summary>
        public static string RecaptchaSiteKey {
            get {
                return ResourceManager.GetString("RecaptchaSiteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security answer.
        /// </summary>
        public static string Security_Answer {
            get {
                return ResourceManager.GetString("Security_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security question.
        /// </summary>
        public static string Security_Question {
            get {
                return ResourceManager.GetString("Security_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification.
        /// </summary>
        public static string SettingEmailVerificationRequired {
            get {
                return ResourceManager.GetString("SettingEmailVerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount websites.
        /// </summary>
        public static string SettingsAmountWebsites {
            get {
                return ResourceManager.GetString("SettingsAmountWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto update.
        /// </summary>
        public static string SettingsAutoUpdate {
            get {
                return ResourceManager.GetString("SettingsAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SettingsDescription {
            get {
                return ResourceManager.GetString("SettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset in &amp; outs.
        /// </summary>
        public static string SettingsIsResetInAndOutsEnabled {
            get {
                return ResourceManager.GetString("SettingsIsResetInAndOutsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string SettingsKeywords {
            get {
                return ResourceManager.GetString("SettingsKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long title.
        /// </summary>
        public static string SettingsLongTitle {
            get {
                return ResourceManager.GetString("SettingsLongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short title.
        /// </summary>
        public static string SettingsShortTitle {
            get {
                return ResourceManager.GetString("SettingsShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slogan.
        /// </summary>
        public static string SettingsSlogan {
            get {
                return ResourceManager.GetString("SettingsSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string SettingsUrl {
            get {
                return ResourceManager.GetString("SettingsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User website monitoring.
        /// </summary>
        public static string SettingsUserServerMonitoringEnabled {
            get {
                return ResourceManager.GetString("SettingsUserServerMonitoringEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
