//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Languages.Admin.Views.Google {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Website {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Website() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Languages.Admin.Views.Google.Website", typeof(Website).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Loading Speed.
        /// </summary>
        public static string AverageLoadingSpeed {
            get {
                return ResourceManager.GetString("AverageLoadingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Time on Site.
        /// </summary>
        public static string AverageTime {
            get {
                return ResourceManager.GetString("AverageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string ChartViews {
            get {
                return ResourceManager.GetString("ChartViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date....
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics.
        /// </summary>
        public static string GoogleAnalyticsTitle {
            get {
                return ResourceManager.GetString("GoogleAnalyticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Bounce Rate.
        /// </summary>
        public static string IncomingBounceRate {
            get {
                return ResourceManager.GetString("IncomingBounceRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miliseconds.
        /// </summary>
        public static string Miliseconds {
            get {
                return ResourceManager.GetString("Miliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Visitors.
        /// </summary>
        public static string NewVisitors {
            get {
                return ResourceManager.GetString("NewVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing Bounce Rate.
        /// </summary>
        public static string OutgoingBounceRate {
            get {
                return ResourceManager.GetString("OutgoingBounceRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages Per Visit.
        /// </summary>
        public static string PagesPerVisit {
            get {
                return ResourceManager.GetString("PagesPerVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pageviews.
        /// </summary>
        public static string PageViews {
            get {
                return ResourceManager.GetString("PageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Referrals.
        /// </summary>
        public static string Referral {
            get {
                return ResourceManager.GetString("Referral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Usage.
        /// </summary>
        public static string SiteUsage {
            get {
                return ResourceManager.GetString("SiteUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date....
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Pages.
        /// </summary>
        public static string TopPages {
            get {
                return ResourceManager.GetString("TopPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Referrals.
        /// </summary>
        public static string TopReferral {
            get {
                return ResourceManager.GetString("TopReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Searches.
        /// </summary>
        public static string TopSearches {
            get {
                return ResourceManager.GetString("TopSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
    }
}
