//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Languages.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Languages.Controllers.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is banned..
        /// </summary>
        public static string AccountBanned {
            get {
                return ResourceManager.GetString("AccountBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been updated..
        /// </summary>
        public static string AccountUpdated {
            get {
                return ResourceManager.GetString("AccountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been successfully verified..
        /// </summary>
        public static string AccountVerified {
            get {
                return ResourceManager.GetString("AccountVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is already activated..
        /// </summary>
        public static string AlreadyActivated {
            get {
                return ResourceManager.GetString("AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already being used..
        /// </summary>
        public static string EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password is incorrect..
        /// </summary>
        public static string IncorrectOldPassword {
            get {
                return ResourceManager.GetString("IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password for this account..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect security answer..
        /// </summary>
        public static string IncorrectSecurity {
            get {
                return ResourceManager.GetString("IncorrectSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP has been blocked for 30 minutes because of too many failed login attempts..
        /// </summary>
        public static string IpBlocked {
            get {
                return ResourceManager.GetString("IpBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new email has been activated..
        /// </summary>
        public static string NewEmailActivated {
            get {
                return ResourceManager.GetString("NewEmailActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found with this code, please check your code and try again..
        /// </summary>
        public static string NoAccountFoundCode {
            get {
                return ResourceManager.GetString("NoAccountFoundCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found with the given email..
        /// </summary>
        public static string NoAccountFoundEmail {
            get {
                return ResourceManager.GetString("NoAccountFoundEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no account with the given username..
        /// </summary>
        public static string NoAccountFoundUsername {
            get {
                return ResourceManager.GetString("NoAccountFoundUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not verified yet..
        /// </summary>
        public static string NotVerified {
            get {
                return ResourceManager.GetString("NotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset and send to your email..
        /// </summary>
        public static string PasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("PasswordResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username has been send to your email..
        /// </summary>
        public static string UsernameSuccessfullySend {
            get {
                return ResourceManager.GetString("UsernameSuccessfullySend", resourceCulture);
            }
        }
    }
}
