//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Languages.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Website {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Website() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Languages.Controllers.Website", typeof(Website).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your website has been added..
        /// </summary>
        public static string AddedSuccesfully {
            get {
                return ResourceManager.GetString("AddedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your website has been deleted..
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid answer..
        /// </summary>
        public static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field reason has to be a minimum of 25 characters long..
        /// </summary>
        public static string InvalidReasonField {
            get {
                return ResourceManager.GetString("InvalidReasonField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vote, please check your url and see if the parameters are correct..
        /// </summary>
        public static string InvalidVote {
            get {
                return ResourceManager.GetString("InvalidVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website doesn&apos;t exist..
        /// </summary>
        public static string NoWebsiteFound {
            get {
                return ResourceManager.GetString("NoWebsiteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is on the blacklist..
        /// </summary>
        public static string OnBlackList {
            get {
                return ResourceManager.GetString("OnBlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rating has been added successfully..
        /// </summary>
        public static string RateAdded {
            get {
                return ResourceManager.GetString("RateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website has been reported..
        /// </summary>
        public static string WebsiteReportedSuccessfully {
            get {
                return ResourceManager.GetString("WebsiteReportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your website has been updated..
        /// </summary>
        public static string WebsiteUpdated {
            get {
                return ResourceManager.GetString("WebsiteUpdated", resourceCulture);
            }
        }
    }
}
