//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Languages.Admin.Views.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Languages.Admin.Views.Settings.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New users have to be approved first by administrators before they can login and list their website..
        /// </summary>
        public static string AdminVerification {
            get {
                return ResourceManager.GetString("AdminVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically download and install updates for: Desko, widgets and themes..
        /// </summary>
        public static string AutoUpdateDescription {
            get {
                return ResourceManager.GetString("AutoUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create thumbnails of user websites.
        /// </summary>
        public static string CreateThumbnails {
            get {
                return ResourceManager.GetString("CreateThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronjobs.
        /// </summary>
        public static string CronjobsTab {
            get {
                return ResourceManager.GetString("CronjobsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email users their website statistics (in &amp; out) from the past 7 days..
        /// </summary>
        public static string EmailUserWebsiteStatisticsDescription {
            get {
                return ResourceManager.GetString("EmailUserWebsiteStatisticsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users need to verify their e-mailadress.
        /// </summary>
        public static string EmailVerification {
            get {
                return ResourceManager.GetString("EmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set in maintenance mode.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor the servers of users.
        /// </summary>
        public static string MonitorWebsites {
            get {
                return ResourceManager.GetString("MonitorWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha.
        /// </summary>
        public static string RecaptchaTab {
            get {
                return ResourceManager.GetString("RecaptchaTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clean all the in &amp; outs from the users websites?.
        /// </summary>
        public static string ResetInAndOutsDescription {
            get {
                return ResourceManager.GetString("ResetInAndOutsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeTab {
            get {
                return ResourceManager.GetString("ThemeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Settings.
        /// </summary>
        public static string UpdateSettings {
            get {
                return ResourceManager.GetString("UpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the update when the software version mismatches the update software version..
        /// </summary>
        public static string UpdateWhenIncorrectVersionDescription {
            get {
                return ResourceManager.GetString("UpdateWhenIncorrectVersionDescription", resourceCulture);
            }
        }
    }
}
