//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminNavigation
    {
        public int Id { get; set; }
        public Nullable<int> WidgetId { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string LocalizedName { get; set; }
        public string LocalizedBase { get; set; }
        public string Icon { get; set; }
        public Nullable<int> PluginId { get; set; }
        public Nullable<int> ThemeId { get; set; }
    
        public virtual Plugins Plugins { get; set; }
        public virtual Widgets Widgets { get; set; }
        public virtual Themes Themes { get; set; }
    }
}
