//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAccounts
    {
        public int Id { get; set; }
        public string SMTPEmail { get; set; }
        public string SMTPPassword { get; set; }
        public string SMTPServer { get; set; }
        public bool SMTPSecure { get; set; }
        public int SMTPPort { get; set; }
    }
}
