//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        public Languages()
        {
            this.Settings = new HashSet<Settings>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Culture { get; set; }
        public string Abbreviation { get; set; }
    
        public virtual ICollection<Settings> Settings { get; set; }
    }
}
