//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginFails
    {
        public long Id { get; set; }
        public string Ip { get; set; }
        public byte Attempts { get; set; }
        public System.DateTime ExpireDate { get; set; }
    }
}
