//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavigationPages
    {
        public NavigationPages()
        {
            this.NavigationPages1 = new HashSet<NavigationPages>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public int OrderNumber { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<NavigationPages> NavigationPages1 { get; set; }
        public virtual NavigationPages NavigationPages2 { get; set; }
    }
}
