//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PluginUpdateSettings
    {
        public int Id { get; set; }
        public System.DateTime LastCheckedDate { get; set; }
        public bool IsChecking { get; set; }
        public bool IsInstalling { get; set; }
        public bool IsDownloading { get; set; }
        public bool IsUpdatingSuccess { get; set; }
    }
}
