//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll
    {
        public Poll()
        {
            this.PollAnswers = new HashSet<PollAnswers>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<PollAnswers> PollAnswers { get; set; }
    }
}
