//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string SenderIP { get; set; }
        public int WebsiteId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Websites Websites { get; set; }
    }
}
