//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeoPages
    {
        public int Id { get; set; }
        public string PageController { get; set; }
        public string PageIndex { get; set; }
        public string ResourceTitleName { get; set; }
        public string ResourceDescriptionName { get; set; }
        public string ResourceBaseName { get; set; }
    }
}
