//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Themes
    {
        public Themes()
        {
            this.Settings = new HashSet<Settings>();
            this.ThemeOpenUpdates = new HashSet<ThemeOpenUpdates>();
            this.WidgetsThemeSection = new HashSet<WidgetsThemeSection>();
            this.ActiveDlls = new HashSet<ActiveDlls>();
            this.AdminBreadcrumbs = new HashSet<AdminBreadcrumbs>();
            this.AdminNavigation = new HashSet<AdminNavigation>();
        }
    
        public int Id { get; set; }
        public string ThemeName { get; set; }
        public string AuthorName { get; set; }
        public string AuthorUrl { get; set; }
        public string FolderName { get; set; }
        public string Version { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string UpdateUrl { get; set; }
    
        public virtual ICollection<Settings> Settings { get; set; }
        public virtual ICollection<ThemeOpenUpdates> ThemeOpenUpdates { get; set; }
        public virtual ICollection<WidgetsThemeSection> WidgetsThemeSection { get; set; }
        public virtual ICollection<ActiveDlls> ActiveDlls { get; set; }
        public virtual ICollection<AdminBreadcrumbs> AdminBreadcrumbs { get; set; }
        public virtual ICollection<AdminNavigation> AdminNavigation { get; set; }
    }
}
