//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteIn
    {
        public int WebsiteID { get; set; }
        public string IP { get; set; }
        public bool Unique { get; set; }
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Websites Websites { get; set; }
    }
}
