//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteOutDaily
    {
        public long Id { get; set; }
        public int WebsiteId { get; set; }
        public System.DateTime Date { get; set; }
        public int UniqueOut { get; set; }
        public int TotalOut { get; set; }
    
        public virtual Websites Websites { get; set; }
    }
}
