//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Websites
    {
        public Websites()
        {
            this.Reports = new HashSet<Reports>();
            this.WebsiteIn = new HashSet<WebsiteIn>();
            this.WebsiteInDaily = new HashSet<WebsiteInDaily>();
            this.WebsiteOut = new HashSet<WebsiteOut>();
            this.WebsiteOutDaily = new HashSet<WebsiteOutDaily>();
            this.WebsiteRating = new HashSet<WebsiteRating>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string BannerURL { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public string Keywords { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool Sponsored { get; set; }
        public string ServerIP { get; set; }
        public Nullable<int> ServerPort { get; set; }
        public Nullable<System.DateTime> MonitorCheckedDate { get; set; }
        public bool IsOnline { get; set; }
        public string BannerFileName { get; set; }
        public string Thumbnail { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Reports> Reports { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<WebsiteIn> WebsiteIn { get; set; }
        public virtual ICollection<WebsiteInDaily> WebsiteInDaily { get; set; }
        public virtual ICollection<WebsiteOut> WebsiteOut { get; set; }
        public virtual ICollection<WebsiteOutDaily> WebsiteOutDaily { get; set; }
        public virtual ICollection<WebsiteRating> WebsiteRating { get; set; }
    }
}
