//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetsThemeSection
    {
        public WidgetsThemeSection()
        {
            this.WidgetsTheme = new HashSet<WidgetsTheme>();
        }
    
        public int Id { get; set; }
        public int ThemeId { get; set; }
        public string FriendlyName { get; set; }
        public string CodeName { get; set; }
    
        public virtual Themes Themes { get; set; }
        public virtual ICollection<WidgetsTheme> WidgetsTheme { get; set; }
    }
}
