//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widgets
    {
        public Widgets()
        {
            this.ActiveDlls = new HashSet<ActiveDlls>();
            this.AdminBreadcrumbs = new HashSet<AdminBreadcrumbs>();
            this.AdminNavigation = new HashSet<AdminNavigation>();
            this.WidgetOpenUpdates = new HashSet<WidgetOpenUpdates>();
            this.WidgetsTheme = new HashSet<WidgetsTheme>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string AreaName { get; set; }
        public string Version { get; set; }
        public string Author { get; set; }
        public string AuthorUrl { get; set; }
        public string Controller { get; set; }
        public string StartIndex { get; set; }
        public string Namespace { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string UpdateUrl { get; set; }
    
        public virtual ICollection<ActiveDlls> ActiveDlls { get; set; }
        public virtual ICollection<AdminBreadcrumbs> AdminBreadcrumbs { get; set; }
        public virtual ICollection<AdminNavigation> AdminNavigation { get; set; }
        public virtual ICollection<WidgetOpenUpdates> WidgetOpenUpdates { get; set; }
        public virtual ICollection<WidgetsTheme> WidgetsTheme { get; set; }
    }
}
